spring:
  datasource:
    url: jdbc:h2:mem:user
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
user:
  url: https://api.github.com/users
  updateSql: UPDATE USER_INFORMATION SET REQUEST_COUNT = REQUEST_COUNT + 1 WHERE LOGIN = ?
  insertSql: INSERT INTO USER_INFORMATION VALUES (?, 1)