openapi: "3.0.0"
info:
  version: 1.0.0
  title: User API
servers:
  - url: http://localhost:8080/
paths:
  /users/{login}:
    get:
      summary: Info for a specific user
      tags:
        - users
      parameters:
        - name: login
          in: path
          required: true
          description: The login of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      required:
        - id
        - login
        - name
        - type
        - avatarUrl
        - createdAt
        - calculations
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        name:
          type: string
        type:
          type: string
        avatarUrl:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
        calculations:
          type: number
          format: dobule
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string